on: 
  workflow_dispatch:
    inputs:
      account_sid:
        description: 'ACCOUNT SID'     
        required: true
      account_secret:
        description: 'ACCOUNT SECRET'
        required: true
jobs:
  deployFlexPlugin:
    runs-on: ubuntu-latest
    
    strategy:
      matrix:
        node-version: [12.x]
    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}
    - run: npm install twilio-cli -g
    - run: twilio plugins:install @twilio-labs/plugin-flex
    - run: export TWILIO_ACCOUNT_SID=${{ github.event.inputs.account_sid }}
    - run: export TWILIO_AUTH_TOKEN=${{ github.event.inputs.account_secret }}
    - run: npm install
    - working-directory: ./plugin-flex-did
    - run: twilio flex:plugins:deploy --changelog "Deploying flex-did"
    - working-directory: ./plugin-flex-did
    - run: twilio flex:plugins:release --plugin plugin-flex-did@0.0.1 --name "Flex DID" --description "Provides direct inward dial functionality."
